### ISSUE TITLE
Unable to create landscape using USGS 1/3”

### ISSUE THREAD

**Issue by 1NoobDev** [LandscapeCombinator/LandscapeCombinator#14]
I'm using the 0.5.1 release in UE5.2.1. Got my data.txt as instructed from the [USGS National Map Data Download Application](https://apps.nationalmap.gov/downloader/), downloaded to my device. It's downloading the file, but after that I get the following error.

```Internal GDALWarp error (0) while converting dataset from file E:/Program Files/Epic Games/UE_5.2/Engine/Intermediate/LandscapeCombinator/USGS_13_n39w106_20230602.tif to EPSG 4,326.```

![image](https://github.com/LandscapeCombinator/LandscapeCombinator/assets/20015201/bf7f775d-79bf-4320-9606-e296fc3b2b35)

**Comment by LandscapeCombinator** [comment]
It looks like you followed the instructions correctly, sorry it didn't work. Can you please send the txt file so that I look into it? In the meantime you can try removing the `LevelCoordinates` actor, so that it does not reproject to EPSG 4326. In that case the `LevelCoordinates` should be created automatically when you press `Spawn Landscape`.

Also that's probably nothing, but it shouldn't be displayed as EPSG 4,326, I'll fix this too.

**Comment by LandscapeCombinator** [comment]
Hi @1NoobDev, were you able to double-check this after deleting the file on your computer?

**Comment by LandscapeCombinator** [comment]
This should be working now, please reopen if you encounter this issue again. Thanks you again for reporting this
